language: python
python:
- 3.7.8
- 3.8
- 3.9
branches:
  only:
  - master
  - dev
env:
  global:
  - PYTHONPATH=.:vendor
install:
- pip install .
script:
- python -m unittest discover tests --failfast
