language: python
python:
  - "2.7"
  - "3.7"

branches:
  only:
  - master
  - dev

env:
  global:
    - PYTHONPATH=.:vendor

install:
  - "pip install -r requirements.txt"

script:
  - "python -m unittest discover tests --failfast"
